version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - my_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro

volumes:
  my_data:
